In [58]:
import numpy as np 
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import SGDClassifier

In [59]:
data=pd.read_csv('Assignment8.csv')

In [60]:
data.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

### Binary Classification

In [66]:
data['race/ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [67]:
data['parental level of education'].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [70]:
data.lunch.unique()

array(['standard', 'free/reduced'], dtype=object)

In [71]:
data['test preparation course'].unique()

array(['none', 'completed'], dtype=object)

In [72]:
series1=data['parental level of education'].map({"bachelor's degree":1, 'some college':2,"master's degree":3,"associate's degree":4
                                    ,'high school':5, 'some high school':6})
series2=data['test preparation course'].map({'none':1,"completed":2})
series3=data['lunch'].map({'standard':1,'free/reduced':2})
series4=data['gender'].map({"female":1,"male":2})

In [73]:
df=data.drop(['gender','parental level of education','lunch','test preparation course'],axis=1)

In [74]:
df

race/ethnicity  math score  reading score  writing score
0          group B          72             72             74
1          group C          69             90             88
2          group B          90             95             93
3          group A          47             57             44
4          group C          76             78             75
..             ...         ...            ...            ...
995        group E          88             99             95
996        group C          62             55             55
997        group C          59             71             65
998        group D          68             78             77
999        group D          77             86             86

[1000 rows x 4 columns]

In [75]:
df['gender']=series4

In [76]:
df['parental level of education']=series1

In [77]:
df['lunch']=series3

In [78]:
df["test preparation course"]=series2

In [79]:
df


race/ethnicity  math score  reading score  writing score  gender  \
0          group B          72             72             74       1   
1          group C          69             90             88       1   
2          group B          90             95             93       1   
3          group A          47             57             44       2   
4          group C          76             78             75       2   
..             ...         ...            ...            ...     ...   
995        group E          88             99             95       1   
996        group C          62             55             55       2   
997        group C          59             71             65       1   
998        group D          68             78             77       1   
999        group D          77             86             86       1   

     parental level of education  lunch  test preparation course  
0                              1      1                        1  
1                              2      1                        2  
2                              3      1                        1  
3                              4      2                        1  
4                              2      1                        1  
..                           ...    ...                      ...  
995                            3      1                        2  
996                            5      2                        1  
997                            5      2                        2  
998                            2      1                        2  
999                            2      2                        1  

[1000 rows x 8 columns]

In [80]:
y =df["race/ethnicity"]

In [81]:
for i in range(len(y)):
    
    if y[i]=='group A':
        
        y[i]=1
        
    else:
        
        y[i]=0

C:\Users\Pegah Khazaie\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Pegah Khazaie\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [82]:
y

0      0
1      0
2      0
3      1
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: race/ethnicity, Length: 1000, dtype: object

In [83]:
X = df[['gender','parental level of education','lunch','test preparation course','math score','reading score','writing score']]

In [84]:
X

gender  parental level of education  lunch  test preparation course  \
0         1                            1      1                        1   
1         1                            2      1                        2   
2         1                            3      1                        1   
3         2                            4      2                        1   
4         2                            2      1                        1   
..      ...                          ...    ...                      ...   
995       1                            3      1                        2   
996       2                            5      2                        1   
997       1                            5      2                        2   
998       1                            2      1                        2   
999       1                            2      2                        1   

     math score  reading score  writing score  
0            72             72             74  
1            69             90             88  
2            90             95             93  
3            47             57             44  
4            76             78             75  
..          ...            ...            ...  
995          88             99             95  
996          62             55             55  
997          59             71             65  
998          68             78             77  
999          77             86             86  

[1000 rows x 7 columns]

In [85]:
# for i in range(len(y)):
#     if y[i]==1:
#         print(i)
    

In [86]:
X_train, X_test, y_train, y_test = X[:900], X[900:], y[:900], y[900:]

In [87]:
X_train=np.array(X_train)

In [88]:
shuffle_index = np.random.permutation(900)
X_train, y_train = X_train[shuffle_index],y_train[shuffle_index]

In [89]:
y_train_A = (y_train == 1)
y_test_A = (y_test == 1)

In [90]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train_A)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [91]:
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
skfolds = StratifiedKFold(n_splits=3,random_state=42)
for train_index, test_index in skfolds.split(X_train, y_train_A):
    clone_clf = clone(sgd_clf)
    X_train_folds = X_train[train_index]
    y_train_folds = y_train_A[train_index]
    X_test_fold = X_train[test_index]
    y_test_fold = y_train_A[test_index]
    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    n_correct = sum(y_pred == y_test_fold)
    print(n_correct / len(y_pred))

0.9333333333333333
0.8833333333333333
0.92


C:\Users\Pegah Khazaie\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [92]:
cross_val_score(sgd_clf, X_train, y_train_A, cv=3,scoring="accuracy")

array([0.90666667, 0.9       , 0.91333333])

In [93]:
from sklearn.base import BaseEstimator
class Never5Classifier(BaseEstimator):
    
    def fit(self, X, y=None):
        pass
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)

In [94]:
never_A_clf = Never5Classifier()
cross_val_score(never_A_clf, X_train, y_train_A, cv=3, scoring="accuracy")

array([0.92333333, 0.92      , 0.9       ])

In [95]:
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd_clf, X_train, y_train_A, cv=3)

In [96]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train_A, y_train_pred)

array([[820,   3],
       [ 76,   1]], dtype=int64)

In [97]:
y_train_perfect_predictions = y_train_A

In [100]:
confusion_matrix(y_train_A, y_train_perfect_predictions)

array([[823,   0],
       [  0,  77]], dtype=int64)

### Multiclass Classification

In [101]:
y=data['race/ethnicity']

In [102]:
X_train, X_test, y_train, y_test = X[:900], X[900:], y[:900], y[900:]

In [103]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [104]:
sgd_clf.predict([np.array(X)[0]])

array(['group D'], dtype='<U7')

In [105]:
A= sgd_clf.decision_function([np.array(X)[0]])

In [106]:
A

array([[ -895.31440051, -1180.08270547,  -797.10735763,    19.28234579,
         -940.2401705 ]])

In [108]:
np.argmax(A)

3

In [109]:
sgd_clf.classes_

array(['group A', 'group B', 'group C', 'group D', 'group E'], dtype='<U7')

In [110]:
from sklearn.multiclass import OneVsOneClassifier
ovo_clf = OneVsOneClassifier(SGDClassifier(random_state=42))
ovo_clf.fit(X_train, y_train)
ovo_clf.predict([np.array(X)[0]])

array(['group C'], dtype=object)

In [111]:
forest_clf = RandomForestClassifier()


In [112]:
from sklearn.ensemble import RandomForestClassifier
forest_clf.fit(X_train, y_train)
forest_clf.predict([np.array(X)[0]])

array(['group B'], dtype=object)

In [113]:
forest_clf.predict_proba([np.array(X)[0]])

array([[0.  , 0.68, 0.19, 0.12, 0.01]])

In [114]:
cross_val_score(sgd_clf, X_train, y_train, cv=3, scoring="accuracy")

array([0.22333333, 0.22333333, 0.15666667])

In [115]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring="accuracy")

array([0.22333333, 0.31333333, 0.29333333])

In [116]:
y_train_pred = cross_val_predict(sgd_clf, X_train_scaled, y_train, cv=3)
conf_mx = confusion_matrix(y_train, y_train_pred)
conf_mx

array([[  8,  14,  38,   9,   8],
       [ 12,  35, 100,   6,  25],
       [ 23,  68, 144,  16,  40],
       [ 20,  44, 107,  28,  31],
       [ 13,  34,  46,   6,  25]], dtype=int64)